import { PropRow } from "@/components/mdx/props-table";

export const downloadButtonProps: PropRow[] = [
  { name: "platform", type: '"mac" | "windows" | "linux" | "custom"', description: "Selects the default label, icon and download URL from the built-in platform config. Defaults to \"custom\"." },
  { name: "label", type: "React.ReactNode", description: "Overrides the label text/node. Falls back to the platform's default label." },
  { name: "icon", type: "React.ReactNode", description: "Overrides the icon. Falls back to the platform's default icon." },
  { name: "iconPosition", type: '"left" | "right"', description: "Side of the label the icon is rendered on. Defaults to \"left\"." },
  { name: "showIcon", type: "boolean", description: "Whether to render the icon at all. Defaults to true." },
  { name: "as", type: '"button" | "a"', description: "Renders a native <button> or an <a> (needed for direct file downloads). Defaults to \"button\"." },
  { name: "href", type: "string", description: "Download URL, used when as=\"a\". Falls back to the platform's downloadUrl." },
  { name: "fileName", type: "string", description: "Filename hint passed to the anchor's download attribute." },
  { name: "target", type: "string", description: "Anchor target, only applied when as=\"a\"." },
  { name: "rel", type: "string", description: "Anchor rel. Defaults to \"noopener noreferrer\" when target=\"_blank\"." },
  { name: "borderRadius", type: '"none" | "sm" | "md" | "lg" | "full"', description: "Controls height, min-width, font size and icon size. Padding stays fixed across sizes. Defaults to \"md\"." },
  { name: "size", type: '"sm" | "md" | "lg" | "xl"', description: "Controls height, min-width, font size and icon size. Padding stays fixed across sizes. Defaults to \"md\"." },
  { name: "isLoading", type: "boolean", description: "Shows the loading label/icon and disables interaction." },
  { name: "loadingText", type: "React.ReactNode", description: "Label shown while isLoading is true." },
  { name: "loadingIcon", type: "React.ReactNode", description: "Icon shown while isLoading is true." },
  { name: "disabled", type: "boolean", description: "Disables the button and blocks clicks." },
  { name: "className", type: "string", description: "Full override of the outer shell's classes (structure + size + color). Use colorClassName instead for simple recoloring." },
  { name: "wrapperClassName", type: "string", description: "Full override of the inner content-pill classes. Use wrapperColorClassName instead for simple recoloring." },
  { name: "colorClassName", type: "string", description: "Background/text/border/hover classes for the outer shell only — shape, size and shadow are preserved." },
  { name: "wrapperColorClassName", type: "string", description: "Background/text/hover classes for the inner pill only — shape and padding are preserved." },
  { name: "iconClassName", type: "string", description: "Extra classes applied to the icon wrapper span." },
  { name: "onDownloadStart", type: "(platform: Platform) => void", description: "Called right before the click is handled." },
  { name: "onDownloadComplete", type: "(platform: Platform) => void", description: "Called after onClick resolves without throwing." },
  { name: "onDownloadError", type: "(error: Error) => void", description: "Called if onClick throws during the download flow." },
  { name: "children", type: "React.ReactNode", description: "Overrides the label entirely, takes priority over label and the platform default." },
];
